### ISSUE TITLE
Problems creating multiple specs at once

### ISSUE THREAD

**Issue by WesCossick** [vapor-ware/ksync#145]
In my testing, creating two or more specs right after one another causes the `ksync watch` process to stop working correctly. Usually it starts by giving the following error, or something similar:

```
ERRO[0092] Get http://localhost:8384/rest/system/config: dial tcp [::1]:8384: getsockopt: connection refused  ContainerName= LocalPath="/Users/example/Documents/source" Name=crisp-macaque Namespace=local-development Pod= Reload=true RemotePath=/usr/share/nginx/html Selector="tier=example"
```

Then it just repetitively presents these errors:

```
WARN[0033] Get http://localhost:8384/rest/events?since=1849: dial tcp [::1]:8384: getsockopt: connection refused 
WARN[0034] Get http://localhost:8384/rest/events?since=1849: dial tcp [::1]:8384: getsockopt: connection refused 
WARN[0035] Get http://localhost:8384/rest/events?since=1849: dial tcp [::1]:8384: getsockopt: connection refused 
WARN[0035] Get http://localhost:8384/rest/events?since=1849: dial tcp [::1]:8384: getsockopt: connection refused 
```

This also happens when the `ksync watch` process isn't running, and there are several specs that have been created, and you try to launch `ksync watch`.

This does not happen, though, if `ksync watch` is already running with no specs, and you slowly create one spec after another, with about 15-30 seconds in between.

**Comment by WesCossick** [comment]
For context, I'm running `ksync` and `minikube` locally on a MacBook Pro.

**Comment by WesCossick** [comment]
We've stopped using ksync because we couldn't get it to work reliably, but if I recall correctly it was creating them about once a second, maybe faster. It's possible that the cluster we were running was simply consuming too many resources. We've had to scale it back considerably to get it to run locally on our MacBook Pros.

**Comment by timfallmk** [comment]
@grampelberg Just finished digging around in this and it'll be a little more complicated than it seems. `syncthing` is built to restart on any config change, with the monitor process detecting the change and bring it back up. If changes come during downtime `grpc` calls fail and `syncthing`'s config will get into an intermediate state that it doesn't recover from.

The simplest fix would probably be to implement a delay write changes (maybe delete?) that ensures all changes are batched before they are written. Otherwise we'll have to implement some sort of basic queuing system for updates.

I'll take a look at the former and see if this is viable.
