### ISSUE TITLE
Augment for Swarm

### ISSUE THREAD

**Issue by thejmazz** [vapor-ware/ksync#173]
Was hoping I could take a stab at this, as I'd like something similar for Swarm. Some things I've noticed that would need to be changed are:

- swarm has no port-forwarding like `kubectl port-forward`. This can be replaced with a hacky ssh and/or socat solution, or just leave it be and publish the syncthing port on the swarm ingress network (but maybe that won't work b/c it will load balance across each container.) So then publish 5001,5002,5003,etc?
- swarm can use `--mode global` to launch a service on each node, similar to K8's DaemonSet. Instead of sticking radar and ksync in the same pod, they would exist as services under the same stack (get different cluster IP)
- swarm doesn't do `--privileged` atm for services, but I don't think thats a concern, seems ksync and radar just need to volume mount some folders
- the logic for setting up folders would probably be pretty similar, if not exact
- your code's structs assume a K8's environment (e.g. "pod"). Perhaps this same vocabulary can be used "incorrectly" with swarm, or certain chunks of code will need to be quite modified - I would approach this with a "just make it work" attitude at first, then after come back and see if it would be reasonable to account for K8s *and* Swarm within ksync.

Thanks for the great architecture document, without it I would not have been able to peruse the codebase as easily. I have some further questions:

- where in the code does it take the spec list and convert each item to a valid syncthing configuration?
- the way I read it, ksync will find out where within `/var/lib/docker/containers/x/...` the remote folder exists, and sync to that. How does it handle volumes?

*Some ideas on alternate, potentially simpler (hmm, hardly), implementations*

My use case is I would like to develop apps from scratch on a cluster, so that I do not need to `go get`/`npm install`, `docker build`, etc locally while on data (and cause cool!).

- I've been looking into various volume drivers (NFS, CephFS) and container attached storage solutions (Portworx-dev, OpenEBS) to see if any of them are reasonable to have a client (i.e. developer's laptop) mount the remote fs or set up a FUSE, or something, to sync a local folder with a remote volume. I haven't tried this, but one issue could be networking depending on how the orchestrator/CNI is handled.
- Perhaps set up the client/server sync pair on a per-project basis, implemented as extra containers who have syncthing/seafile inside them, you could deploy to cluster and then develop locally with docker run or compose, and have your local volume container connect to the remote. `-v $(pwd):/data` into local volume container, which syncs up with remote volume container, and then the app container takes `volumes_from` or something similar to grab files from the remove volume container (hmmm, volumes_from would only work if containers on same node...)
- good'ol rsync (one way syncing could be fine, dev -> cluster), or even [bitpocket](https://github.com/sickill/bitpocket)
- seems at the very least, need a connection from laptop to cluster (port forward, published port, those + ssh for the rsync approach)
- along the lines of an idea above, limit the syncing to only run on volumes, perhaps this could simplify implementation (e.g. no more restart to grab new mounts?)
- the reason I like the "only sync an explicit volume" idea is because I currently set up development environments to expose a volume where code should go

In the past I've done this with a local file watch that triggers rsync, hardcoded to a specific path in a specific node.

**Comment by timfallmk** [comment]
@thejmazz Thanks for adding this. I think the tl;dr is that swarm support would take a major rework of the structure. I'm not saying it shouldn't be done, just that a lot would need to be done.

Let me address some of your questions, and that should hopefully give you some more insight:

>where in the code does it take the spec list and convert each item to a valid syncthing configuration?

Syncthing has a notion of "devices" (basically remotes) and "folders" (locations to sync). If you follow the call chain from `create` you'll see that we basically create a spec from the definition provided, construct a spec list from than and any other changes, and parse that output into syncthing's expected XML format. Then we roll both processes, as well as the remote process (in that case roll the whole container).

The process is something like: `create -> spec -> speclist -> service -> folder`. The syncthing config is written out by folder (using the syncthing lib) directly onto disk before syncthing is restarted.

_This last part is actually a little wonky, as it manages the config outside of syncthing's view. This can cause issues when adding/deleting multiple specs rapidly. We're working on a better way of doing this._

>the way I read it, ksync will find out where within /var/lib/docker/containers/x/... the remote folder exists, and sync to that. How does it handle volumes?

This part is similarly wonky. Docker doesn't update a mount table after a container is running, even if it changes on disk. The way we get around this is to manage the files in the graphdriver filesystem and then roll ("hot reload") the container after we make changes. Since all volumes are handled the same way on the graphdriver side ("native" and "mounted" volumes), it doesn't really matter whether it's an exported volume or not as long as it's present when the container starts.

There's a draw back to approach, as it makes certain assumptions about the graphdriver and how it lays out it's filesystem layers. That's mostly why we can't support certain graphdrivers (`aufs`), and why we're investigating supporting others #161 .

I hope that gives you a better understanding of how things work. My understanding is that Docker is doing some work to deprecate/merge/make compatible swarm and kubernetes (there's an experimental feature in the desktop version of Docker that lets you use either k8s or swarm as a deployment manager for k8s). It will be interesting to see if this becomes more of possibility as the two grow closer together.

**Comment by grampelberg** [comment]
>where in the code does it take the spec list and convert each item to a valid syncthing configuration?

@timfallmk got it, the config is entirely handled via syncthing's REST API (https://github.com/vapor-ware/ksync/blob/local-config-over-grpc/pkg/syncthing/folder.go#L22).

>the way I read it, ksync will find out where within /var/lib/docker/containers/x/... the remote folder exists, and sync to that. How does it handle volumes?

Right now, ksync isn't handling volumes. To support volumes, it would just need to be a little bit more intelligent about paths. The docker daemon reports volumes separately from the container FS, but the data's there.

**Comment by thejmazz** [comment]
FWIW, I am now using K8s exclusively and have no plans to ever work on this. Feel free to close if desired!
