### ISSUE TITLE
"ksync init" and it's subcommands like "ksync init --upgrade" should not delete pods on the remote server without user confirmation.

### ISSUE THREAD

**Issue by ashahba** [vapor-ware/ksync#187]
Seems like `ksync init` and it's subcommands redeploy the `ds/ksync` Pods regardless of them  being present on the server or not.
As an end user my expectation was if the init has already been done and the bits are present on the server side, we don't need to un-deploy the Pods  and redeploy the same exact pods again. 
Specially on relatively large or shared clusters this could be a pretty expensive operation with some unintended downtime.

Same argument holds for `ksync init --upgrade`. Meaning if no new version is available we should not un-deploy Pods on the server only to create same exact versions again.

**Comment by timfallmk** [comment]
@ashahba I see where your concern might be here, however this behavior is purposeful. The daemon set that runs the radar/syncthing portion of ksync is entirely stateless and designed to be blown away/reloaded at will. The upgrade process, if there is a new image, is to pull an update image and relaunch the same ds. It really doesn't hurt to reload it even if there isn't a new image. In addition, since it doesn't touch user data, and runs in the `kube-system` namespace, it should be relatively transparent to the end user.

I'm interested in hearing if you have other concerns around this through. We have considered adding a `dry-run` option #135 to some commands.

**Comment by ashahba** [comment]
The only concern I have is the unwanted downtime when we know for certain that there is no new updated images available. But as far as user data I have seen any loss there.

**Comment by timfallmk** [comment]
I think if we see some problems we can revisit this, otherwise we'll keep it as is.
