### ISSUE TITLE
Use of Radar

### ISSUE THREAD

**Issue by rpunetha** [vapor-ware/ksync#250]
> In addition to querying the docker daemon, radar also issues restart API requests for when the syncthing container or remote container need to be restarted.

Can anyone explain why there's a need to restart remote containers and syncthing containers? I use syncthing in the exact same manner as ksync. However, I never have to restart syncthing container after configuring it with data for new pods. Then why does Radar exist in the ksync system?

**Comment by timfallmk** [comment]
@rpunetha I'm not quite sure I understand your question.

On the remote (k8s cluster) side, there are a pair of pods running in a DaemonSet (for each deployment). One contains the syncthing daemon, the other contains the radar daemon. The remote container, by default, is restarted upon completion of any file sync. The syncthing container is only restarted in certain conditions where state would otherwise be incorrect between the two (updating the list of syncs is one example). I hope this clears up any questions you might have.
