### ISSUE TITLE
Problem with watch

### ISSUE THREAD

**Issue by henres** [vapor-ware/ksync#263]
Problem with watch:

https://pastebin.com/k1JBzJ9a

**Comment by timfallmk** [comment]
Hi @henres . Typically it's best to describe the issue you're having verbally, and to keep any code or logs minimal and within the scope of GitHub. This is just considered good form, and aids with debugging.

I've quickly looked over your log dump, and I don't see anything out of the ordinary. If you're concern is the warning messages about failure to contact the local service, that's normal when it's being restarted. If it never reestablishes connection, then there's a problem. Since you didn't specify what the problem was, I can't really be of more help without more information.

**Comment by henres** [comment]
I'm sorry for this non human issue. I install last version of ksync and this problem doesn't occur anymore. I have now other problem but this is not the issue.

Thanks and sorry for the inconvenience.

**Comment by timfallmk** [comment]
Good to hear!
