### ISSUE TITLE
Question: What is the proper way to shutdown ksync

### ISSUE THREAD

**Issue by BarryDrez** [vapor-ware/ksync#273]
I am starting ksync from Java using ProcessBuilder.  Running ksync watch on Windows which starts ksync_windows_amd64.exe and 2 syncthing.exe(s).  When I shut it down programmatically, the ksync_windows_amd64.exe goes away, byt the 2  syncthing.exe(s) remain.  What is the proper command to stop watching?

**Comment by timfallmk** [comment]
You probably want `ksync clean --local`

**Comment by BarryDrez** [comment]
This does not work on Windows.

**Comment by BarryDrez** [comment]
Why was this closed?

**Comment by timfallmk** [comment]
@BarryDrez A little more background here. Running `ksync watch` on Windows requires running the primary process in the foreground, as daemonization is not supported on that platform. When the primary process exists, it collapses the process group, including killing all child processes. You can see this for yourself by running it in a terminal.

I suspect that whatever you're using to launch the parent process is preventing the normal control of child processes, that's why you're having left overs left behind when it exits.

I'm happy to help debug this with you, but as it isn't an internal ksync issue, I've closed it so it's not in our development tracking.

**Comment by BarryDrez** [comment]
@timfallmk in its simplest form, this is the Java code I used to start ksync: 
```
ProcessBuilder pb = new ProcessBuilder("C:\\ksync\\ksync_windows_amd64.exe", "watch");
pb.directory(new File("C:\\ksync")); 		            
watchProcess = pb.start();
```
I understand your explanation, and I will look into an alternative solution.

**Comment by timfallmk** [comment]
I'm less familiar with Windows (or Process Builder for that matter), but it's likely attaching its own process management to that process, which is interfering.

You might find some inspiration from the way we deal with deamonization on other platforms. Also, it's easy to find (and cleanup) the child processes, by looking for which processes are using the ports given in the config (the *nix equivalent would be using `losf -i`). Hopefully that gives you some ideas.

**Comment by BarryDrez** [comment]
Thank you.  I will do some digging.
